from __future__ import annotations

import logging
import math
from typing import Iterable, Optional, TYPE_CHECKING

from ..numerics.Intersection import ManifoldKey
from .TopologyResults import PseudoneighborPair

if TYPE_CHECKING:
    from .Trellis import Trellis
    from .TrellisBranch import TrellisBranch
    from ..numerics.FixedPoint import FixedPoint

logger = logging.getLogger(__name__)
logger.addHandler(logging.NullHandler())

"""
Dev Notes — Compute-Pseudoneighbors (Pseudoneighbor_Algorithm.pdf)

Two intersections x, x' are a pseudoneighbor pair iff the open stable interval
W^S(x, x') and the open unstable interval W^U(x, x') contain no trellis
intersection nor any iterate M^n (n in Z) of one. For a finite trellis every
pair first appears on the reference window W^S(r_n, r_{n+p}), where r_n is the
end of the stable manifold and p = the branch return period; the pairs found
there are the *reference* pseudoneighbors, and the full trajectories are their
iterates (extend_pseudoneighbor_trajectories).

There is ONE reference window per fixed point, on the chosen strong pip's own
branch, with r_n = the pip itself. The PDF states this subtly: r_n is "THE
intersection with the greatest stable canonical distance" (globally, not per
branch) and it is sufficient to check only that interval. Why it works for a
period-k orbit: the manifold is cut at the pip (cdist c on its branch) and at
the pip's forward iterates on the other branches (c/beta, c/beta^2, ...), and
a pseudoneighbor trajectory walked backward multiplies its stable cdist by
beta per step while cycling branches — so its position RELATIVE to the local
cut is constant within a lap and jumps by lambda_u exactly once per lap, at
the pip's branch. Every trajectory therefore makes its outermost appearance
inside the single window W^S(pip, M^k(pip)); its appearances on the other
branches are the +1 .. +(k-1) forward iterates, generated by
extend_pseudoneighbor_trajectories. Walking each branch's window (the k=1
extrapolation) finds every trajectory k times and treats each copy as an
independent reference — colliding hole propagations (author-reported bug).
Intersections beyond any branch's cut are excluded from N. Without a chosen
strong pip, the globally outermost intersection plays r_n.

Implementation notes:

* p = branch.return_period = k_value. This resolves the open question in
  TrellisBranch's Dev Notes for the non-inversion case (k_value == period);
  the inversion ordering (k_value == 2*period) follows the same branch-cycle
  bookkeeping as StrongPip but is unvalidated for lack of an inversion example.
* The algorithm walks *consecutive* intersections on the stable branch, so the
  open stable interval between a candidate pair is empty by construction; all
  the work is in the unstable-interval check.
* Both members of a pair must lie on the SAME unstable branch: two distinct
  unstable curves (different orbit points, or the two inversion half-branches,
  which join only through the anchor — itself a trellis point) cannot be
  connected by an open unstable arc, so such a pair is rejected outright.
* One map step scales an unstable canonical distance by beta = lambda_u^(1/k)
  (per TangleWorkbench._register_forward_iterate). Trellis.scale_cdist scales
  by lambda_u^n where n counts *full branch returns*, not map steps, so beta is
  computed locally here.
* The all-iterates membership test is closed-form, not a loop over n: a
  candidate r on unstable branch at cycle position pos_r lands on the target
  branch only for step counts n = d + m*k, d = (pos_target - pos_r) mod k,
  where its unstable cdist becomes r_u * beta^d * lambda_u^m. Since
  lambda_u > 1, only finitely many m put that inside the open interval
  (lo, hi); the m-range comes from log ratios and each candidate m is then
  tested against the strict inequalities directly.
* The open interval is STRICT; x0, x1 and their own iterates sit exactly at
  the (scaled) endpoints up to canonical-distance noise and are recognised by
  a 2D endpoint collision (both the landing's unstable AND stable positions
  match an endpoint within collision_rtol — the StrongPip same-point test;
  never the product). A blanket relative shrink of the interval was tried
  first and swallowed GENUINE interior crossings on deep blast levels, where
  interval widths are small relative to the cdist magnitude.
* Check set N = trellis.own_intersection_ids, mirroring StrongPip's
  same-fixed-point restriction: a candidate whose unstable side belongs to a
  different fixed point can never iterate onto this tangle's unstable manifold
  (its key is absent from the branch cycle, so the position lookup drops it).
  A candidate with manifold_a_key None (a point born from an iterated bridge)
  has an unknown unstable branch and is tested conservatively at all k cycle
  residues — this can reject a true pair; revisit if iterated-bridge points
  ever carry their unstable key.
"""


def forward_unstable_branch_cycle(fixed_point: "FixedPoint") -> list[ManifoldKey]:
    """
    Return the fixed point's unstable branches in forward-iteration (M) order.

    Element j maps to element j+1 (mod len) under one application of M — the
    unstable mirror of :func:`~tanglepack.topology.StrongPip.forward_stable_branch_cycle`,
    cycling through the same orbit order (the unstable manifold of z_i maps
    under M to the unstable manifold of M(z_i)). With inversion the branch
    index flips after each full pass around the orbit.

    Args:
        fixed_point: The fixed point whose unstable branches to order.

    Returns:
        List of manifold keys (fixed_point, "unstable", orbit_index,
        branch_index) in forward-iteration order, of length ``k_value``.
    """
    orbit_order = fixed_point.get_iterable_array("unstable")
    branch_indices = fixed_point.get_branch_array()
    cycle: list[ManifoldKey] = []
    for branch_index in branch_indices:
        for orbit_index in orbit_order:
            cycle.append((fixed_point, "unstable", orbit_index, branch_index))
    return cycle


def compute_pseudoneighbors(
    trellis: "Trellis",
    *,
    collision_rtol: float = 1e-2,
    match_rtol: float = 0.05,
    tol: Optional[float] = None,
) -> list[PseudoneighborPair]:
    """
    Find the reference pseudoneighbor pairs (pure query).

    Implements Compute-Pseudoneighbors(T): walk the consecutive intersection
    pairs of the SINGLE reference window W^S(r_n, r_{n+p}) toward the anchor
    and keep each pair whose open unstable interval contains no trellis
    intersection nor any iterate of one.

    There is one reference window per fixed point, not one per branch: r_n is
    the chosen strong pip itself (the intersection with the globally greatest
    stable canonical distance once the manifold is cut at the pip and its
    forward iterates), so only the pip's own branch carries the window. On a
    period-k orbit every pseudoneighbor trajectory makes its first (outermost)
    appearance inside that single window; the appearances on the other
    branches are its forward iterates — generated by
    :func:`extend_pseudoneighbor_trajectories`, never as independent
    references (walking each branch's window would find every trajectory k
    times and collide). Intersections beyond a branch's cut are excluded from
    the check set. Without a chosen strong pip the globally outermost
    intersection plays r_n.

    Args:
        trellis: The Trellis to read intersections and eigen/orbit data from.
        collision_rtol: Relative slack of the 2D endpoint-collision test that
            recognises the pair's own (noisy) endpoint iterates so they never
            disqualify it (both cdists must match an endpoint).
        match_rtol: Relative tolerance for the cdist fallback that locates
            r_{n+p} when the iterate table lacks the forward chain.
        tol: Absolute canonical-distance slack used to recognise the anchor
            artifact. Defaults to the registry's ``cdist_tol``.

    Returns:
        The reference pairs (``is_reference=True``), from the outermost pair
        toward the anchor (per fixed point of the trellis).

    Raises:
        ValueError: If a stable branch's fixed point has no unstable eigenvalue.
    """
    if tol is None:
        tol = trellis.registry.cdist_tol

    # The topological analysis stops the stable manifold at the chosen strong
    # pip (and its iterates on the other branches): intersections beyond a cut
    # are not part of the (conceptually truncated) trellis, so they leave the
    # check set N.
    _cut_ids, cut_cdists = _strong_pip_cuts(trellis)
    candidates = [
        iid
        for iid in trellis.own_intersection_ids
        if _within_cut(trellis.intersection(iid), cut_cdists, tol)
    ]
    pairs: list[PseudoneighborPair] = []

    for fixed_point in trellis.fixed_points:
        branch, r_n = _reference_branch(trellis, fixed_point, tol)
        if branch is None or len(branch) < 2:
            logger.warning(
                "No usable reference window for %r; skipping", fixed_point
            )
            continue

        lambda_u = trellis.lambda_u(fixed_point)
        if lambda_u is None:
            raise ValueError(
                f"Fixed point of stable branch {branch.key} has no unstable "
                "eigenvalue; cannot scale canonical distances."
            )
        cycle = forward_unstable_branch_cycle(fixed_point)
        pos_map, k = {key: i for i, key in enumerate(cycle)}, len(cycle)
        beta = lambda_u ** (1.0 / k)

        r_end = _resolve_reference_end(trellis, branch, r_n, lambda_u, match_rtol)
        if r_end is None:
            logger.warning(
                "Stable branch %s: could not locate r_{n+p} = M^%d(r_n); "
                "skipping (trellis too small for a full reference window?)",
                branch.key,
                branch.return_period,
            )
            continue

        x0 = r_n
        x1 = trellis.next_intersection(x0, "stable", toward_anchor=True)
        while x0 != r_end:
            if x1 is None:
                logger.warning(
                    "Stable branch %s ran out of intersections before r_{n+p}",
                    branch.key,
                )
                break
            if _unstable_interval_is_clear(
                trellis, x0, x1, candidates, pos_map, k, lambda_u, beta,
                collision_rtol, tol,
            ):
                pair = PseudoneighborPair(
                    x0, x1, branch_key=branch.key, is_reference=True, iterate=0
                )
                pair.origin = pair.as_tuple()
                pairs.append(pair)
            x0 = x1
            x1 = trellis.next_intersection(x1, "stable", toward_anchor=True)

    logger.debug("Found %d reference pseudoneighbor pair(s)", len(pairs))
    return pairs


def extend_pseudoneighbor_trajectories(
    trellis: "Trellis",
    references: Iterable[PseudoneighborPair],
    *,
    match_rtol: float = 0.05,
) -> list[PseudoneighborPair]:
    """
    Generate the full pseudoneighbor trajectories from the reference pairs.

    Each reference pair is mapped forward and backward one step at a time,
    emitting a pair per step until a member's image cannot be found. On a
    period-k orbit this is what populates the OTHER branches: the reference
    window lives on the strong pip's branch only, and the trajectory's
    appearance on each remaining branch is its +1 .. +(k-1) forward iterate.
    An image is resolved through the iterate table when a link exists, else
    by the map-free cdist match (stable /beta, unstable *beta per forward
    step, on the next stable branch of the cycle) — truncated trellises often
    lack table links while the image crossings themselves are present.

    Args:
        trellis: The Trellis whose iterate table / registry to walk.
        references: Reference pairs from :func:`compute_pseudoneighbors`.
        match_rtol: Relative tolerance of the cdist fallback match.

    Returns:
        The generated pairs (``is_reference=False``), deduplicated against the
        references and against each other.
    """
    from .StrongPip import forward_stable_branch_cycle

    references = list(references)
    seen = {ref.as_tuple() for ref in references}
    out: list[PseudoneighborPair] = []
    cycle_cache: dict = {}

    for ref in references:
        fixed_point = _pair_fixed_point(trellis, ref)
        if fixed_point is None:
            continue
        if fixed_point not in cycle_cache:
            lambda_u = trellis.lambda_u(fixed_point)
            cycle = forward_stable_branch_cycle(fixed_point)
            cycle_cache[fixed_point] = (
                {key: i for i, key in enumerate(cycle)},
                cycle,
                None if lambda_u is None else lambda_u ** (1.0 / len(cycle)),
            )
        pos_map, cycle, beta = cycle_cache[fixed_point]
        if beta is None:
            logger.warning("No eigenvalue for %r; cannot extend", fixed_point)
            continue

        for direction in (1, -1):
            a, b = ref.intersection_a, ref.intersection_b
            steps = 0
            while True:
                a = _iterate_intersection(
                    trellis, a, direction, pos_map, cycle, beta, match_rtol
                )
                b = _iterate_intersection(
                    trellis, b, direction, pos_map, cycle, beta, match_rtol
                )
                if a is None or b is None:
                    break
                steps += 1
                key = (min(a, b), max(a, b))
                if key in seen:
                    # Images are unique (table links and cdist matches alike),
                    # so a collision means the rest of the chain coincides too.
                    break
                seen.add(key)
                branch_key = trellis.intersection(a).manifold_b_key
                if trellis.intersection(b).manifold_b_key != branch_key:
                    logger.warning(
                        "Iterated pair (%d, %d) landed on different stable "
                        "branches; the iterate table may be inconsistent",
                        a,
                        b,
                    )
                out.append(
                    PseudoneighborPair(
                        a, b, branch_key=branch_key, is_reference=False,
                        iterate=direction * steps, origin=ref.as_tuple(),
                    )
                )

    logger.debug("Extended %d reference pair(s) into %d iterated pair(s)",
                 len(references), len(out))
    return out


def _pair_fixed_point(trellis: "Trellis", pair: PseudoneighborPair):
    """The fixed point owning a pair's stable branch (None if unresolvable)."""
    key = pair.branch_key or trellis.intersection(pair.intersection_a).manifold_b_key
    return None if key is None else key[0]


def _iterate_intersection(
    trellis: "Trellis",
    intersection_id: int,
    direction: int,
    stable_pos_map: dict[ManifoldKey, int],
    stable_cycle: list[ManifoldKey],
    beta: float,
    match_rtol: float,
) -> Optional[int]:
    """M^direction of an intersection: iterate-table link, else cdist match.

    The fallback looks on the neighbouring stable branch of the forward cycle
    for the crossing whose BOTH canonical distances match the scaled values
    (stable /beta^direction, unstable *beta^direction) — never the product
    (see CLAUDE.md on area preservation).
    """
    linked = trellis.iterate(intersection_id, direction)
    if linked is not None:
        return linked

    ix = trellis.intersection(intersection_id)
    key = ix.manifold_b_key
    if key is None or key not in stable_pos_map:
        return None
    target_key = stable_cycle[(stable_pos_map[key] + direction) % len(stable_cycle)]
    branch = trellis.branch(target_key)
    if branch is None:
        return None

    s_target = ix.stable_cdist / (beta**direction)
    u_target = ix.unstable_cdist * (beta**direction)
    for candidate in branch.intersection_ids:
        other = trellis.intersection(candidate)
        if (
            abs(other.stable_cdist - s_target) <= match_rtol * s_target
            and abs(other.unstable_cdist - u_target) <= match_rtol * u_target
        ):
            return candidate
    return None


def _reference_branch(
    trellis: "Trellis", fixed_point: "FixedPoint", tol: float
) -> tuple[Optional["TrellisBranch"], Optional[int]]:
    """The fixed point's single reference branch and its r_n.

    The strong pip's own branch when the chosen pip belongs to this fixed
    point — only that branch carries the reference window; the other branches
    are cut at the pip's iterates and their trajectory appearances come from
    extension. Without a pip, the branch holding the globally outermost
    intersection plays the same role.
    """
    pip = trellis.strong_pip
    if pip is not None:
        ix = trellis.intersection(pip)
        key = ix.manifold_b_key
        if key is not None and key[0] is fixed_point:
            return trellis.branch(key), pip

    best_branch, best_id, best_s = None, None, -math.inf
    for branch in trellis.branches_of(fixed_point, "stable"):
        if not len(branch):
            continue
        outer = branch.ordered_ids(toward_anchor=True)[0]
        s = trellis.intersection(outer).stable_cdist
        if s > tol and s > best_s:
            best_branch, best_id, best_s = branch, outer, s
    if best_branch is not None:
        logger.info(
            "No strong pip on %r; reference window starts at its globally "
            "outermost intersection %s",
            fixed_point,
            best_id,
        )
    return best_branch, best_id


def _strong_pip_cuts(
    trellis: "Trellis",
) -> tuple[dict[ManifoldKey, int], dict[ManifoldKey, float]]:
    """Per stable branch: the strong-pip cut point's id and stable cdist.

    Empty when no strong pip has been chosen.
    """
    cut_ids: dict[ManifoldKey, int] = {}
    cut_cdists: dict[ManifoldKey, float] = {}
    for iid in trellis.strong_pip_cut_points():
        ix = trellis.intersection(iid)
        if ix.manifold_b_key is not None:
            cut_ids[ix.manifold_b_key] = iid
            cut_cdists[ix.manifold_b_key] = ix.stable_cdist
    return cut_ids, cut_cdists


def _within_cut(ix, cut_cdists: dict[ManifoldKey, float], tol: float) -> bool:
    """True unless the intersection lies beyond its branch's strong-pip cut."""
    cut = cut_cdists.get(ix.manifold_b_key)
    return cut is None or ix.stable_cdist <= cut + tol


def _resolve_reference_end(
    trellis: "Trellis",
    branch: "TrellisBranch",
    r_n: int,
    lambda_u: float,
    match_rtol: float,
) -> Optional[int]:
    """Locate r_{n+p} = M^p(r_n): by the iterate table, else by cdist matching."""
    p = branch.return_period

    # Primary: chase the n=+1 links p times (the table stores depth-1 entries).
    current: Optional[int] = r_n
    for _ in range(p):
        current = trellis.iterate(current, 1)
        if current is None:
            break
    if current is not None:
        if trellis.intersection(current).manifold_b_key == branch.key:
            return current
        logger.warning(
            "M^%d(%d) = %d is not on stable branch %s; falling back to cdist match",
            p, r_n, current, branch.key,
        )

    # Fallback: after p steps (one full return) the stable cdist divides by
    # lambda_u and the unstable cdist multiplies by it. Match BOTH cdists
    # individually — never the product (see CLAUDE.md on area preservation).
    ix = trellis.intersection(r_n)
    s_target = ix.stable_cdist / lambda_u
    u_target = ix.unstable_cdist * lambda_u
    for iid in branch.intersection_ids:
        if iid == r_n:
            continue
        other = trellis.intersection(iid)
        if (
            abs(other.stable_cdist - s_target) <= match_rtol * s_target
            and abs(other.unstable_cdist - u_target) <= match_rtol * u_target
        ):
            return iid
    return None


def _unstable_interval_is_clear(
    trellis: "Trellis",
    x0: int,
    x1: int,
    candidates: Iterable[int],
    pos_map: dict[ManifoldKey, int],
    k: int,
    lambda_u: float,
    beta: float,
    collision_rtol: float,
    tol: float,
) -> bool:
    """True if no trellis intersection (or iterate of one) lies on W^U(x0, x1).

    Iterates over ALL n in Z (the definition's X uses the full orbit): a
    backward iterate counts even when it lands on the removed stable tail —
    e.g. the preimages of blasted crossings puncture the interval they land
    on, per the author. The open interval is strict; a landing is skipped only
    when it 2D-collides with an endpoint (both the landing's unstable and
    stable positions match, within ``collision_rtol``) — that is x0/x1's own
    orbit up to cdist noise, the same-point test StrongPip uses.
    """
    ix0 = trellis.intersection(x0)
    ix1 = trellis.intersection(x1)

    u_key = ix0.manifold_a_key
    if u_key is None or u_key != ix1.manifold_a_key:
        return False  # no single unstable arc connects the pair (see Dev Notes)

    pos_target = pos_map.get(u_key)
    if pos_target is None:
        logger.warning("Unstable branch %s missing from the branch cycle", u_key)
        return False

    lo, hi = sorted((ix0.unstable_cdist, ix1.unstable_cdist))
    if hi - lo <= tol or lo <= 0.0:
        return False  # degenerate interval (near-tangency or anchor endpoint)
    endpoints = (
        (ix0.unstable_cdist, ix0.stable_cdist),
        (ix1.unstable_cdist, ix1.stable_cdist),
    )

    log_lambda = math.log(lambda_u)
    for r_id in candidates:
        if r_id == x0 or r_id == x1:
            continue
        r = trellis.intersection(r_id)
        if abs(r.stable_cdist) <= tol and abs(r.unstable_cdist) <= tol:
            continue  # the anchoring fixed point, not a transverse crossing
        if r.unstable_cdist <= tol:
            continue  # no meaningful position along any unstable branch

        if r.manifold_a_key is not None:
            pos_r = pos_map.get(r.manifold_a_key)
            if pos_r is None:
                continue  # foreign unstable manifold: never lands on this branch
            residues: Iterable[int] = ((pos_target - pos_r) % k,)
        else:
            residues = range(k)  # unknown unstable branch: conservative (Dev Notes)

        for d in residues:
            c = r.unstable_cdist * beta**d
            # After d + m*k total steps the cdist is c * lambda_u^m; only
            # finitely many integers m can put it inside (lo, hi).
            m_lo = math.floor(math.log(lo / c) / log_lambda)
            m_hi = math.ceil(math.log(hi / c) / log_lambda)
            for m in range(m_lo, m_hi + 1):
                value = c * lambda_u**m
                if not (lo < value < hi):
                    continue
                steps = d + m * k
                s_value = r.stable_cdist / beta**steps
                if any(
                    abs(value - u_e) <= collision_rtol * u_e + tol
                    and abs(s_value - s_e) <= collision_rtol * s_e + tol
                    for u_e, s_e in endpoints
                ):
                    continue  # the endpoint's own orbit (2D collision), not a puncture
                logger.debug(
                    "Pair (%d, %d) punctured by %d at residue %d, m=%d "
                    "(cdist %.6g in (%.6g, %.6g))",
                    x0, x1, r_id, d, m, value, lo, hi,
                )
                return False
    return True
